# Generated by Django 5.0.3 on 2024-04-16 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0007_event_media_slider'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='media_images/')),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateField(blank=True, null=True)),
                ('updated_at', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PhotoGallary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='photo_gallary/')),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='updated_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='media',
            name='updated_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='cover_photo',
            field=models.ImageField(blank=True, null=True, upload_to='member_images/'),
        ),
    ]
