# Generated by Django 5.0.3 on 2024-04-17 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0008_activities_photogallary_event_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='committee_position',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='activities',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='activites_images/'),
        ),
    ]
