# Generated by Django 5.0.3 on 2024-04-17 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0009_member_committee_position_alter_activities_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='slider',
            name='created_at',
            field=models.DateField(blank=True, null=True),
        ),
    ]
