# Generated by Django 5.0.3 on 2024-04-17 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0010_slider_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slider',
            name='created_at',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
